#!/usr/bin/env python

"""
Data plotting program

A simple test program, aiming to plot the data
"""

from __future__ import print_function

__author__ = "LI Kezhi"
__date__ = "$2017-11-25$"
__version__ = "0.1"

import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

import numpy as np
from scipy import integrate
from scipy.integrate import simps
from lmfit.models import VoigtModel, LinearModel, PolynomialModel
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
# implement the default mpl key bindings
from matplotlib.backend_bases import key_press_handler
from matplotlib.figure import Figure

import sys
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk

from FileDialog import LoadFileDialog


root = Tk.Tk()
root.wm_title("Data plotting")


# Default plotting
fig = Figure(figsize=(5, 4), dpi=100)
axe = fig.add_subplot(111)


# a tk.DrawingArea
figWindow = []
canvas = []
toolbar = []
def createFigWindow(fig):
    '''
    A general method to create a new window for plotting
    Input: fig generated by pyplot
    '''
    figWindow.append(Tk.Tk())
    figIndex = len(figWindow)
    figWindow[-1].wm_title('Figure ' + str(figIndex))
    figWindow[-1].geometry('650x500+500+200')  # To avoid unstable size refreshing
    canvas.append(FigureCanvasTkAgg(fig, figWindow[-1]))
    canvas[-1].show()
    canvas[-1].get_tk_widget().pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

    toolbar.append(NavigationToolbar2TkAgg(canvas[-1], figWindow[-1]))
    toolbar[-1].update()
    canvas[-1]._tkcanvas.pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

    return figWindow[-1], canvas[-1], toolbar[-1]

# Initial plotting window
axe.text(0.3, 0.5, 'Welcome to use this plotting script!')
createFigWindow(fig)

##### Open files #####
fileLabelFrame = Tk.LabelFrame(root, text='Step 1: Select a data file')
fileLabelFrame.pack(side=Tk.TOP, fill=Tk.X)
filename = Tk.StringVar(root)
def openFile():
    '''
    Open a file for inspection
    Effect: open the file in a new window
    Return: the route of the file
    '''
    global filename
    fd = LoadFileDialog(fileButton)
    filename = fd.go()
    text = open(filename, 'r').read()
    newWindow = Tk.Tk()
    preview = Tk.Text(newWindow, width=80, height=40, wrap=Tk.NONE)
    scrollbarX = Tk.Scrollbar(newWindow, orient=Tk.HORIZONTAL)
    scrollbarY = Tk.Scrollbar(newWindow, orient=Tk.VERTICAL)
    scrollbarX.pack(side=Tk.BOTTOM, fill=Tk.X)
    scrollbarY.pack(side=Tk.RIGHT, fill=Tk.Y)
    preview.config(xscrollcommand=scrollbarX.set)
    preview.config(yscrollcommand=scrollbarY.set)
    scrollbarX.config(command=preview.xview)
    scrollbarY.config(command=preview.yview)
    preview.pack(fill=Tk.BOTH)
    preview.insert(Tk.INSERT, str(text))
fileButton = Tk.Button(fileLabelFrame, text='Open...', command=openFile)
fileButton.pack(side=Tk.LEFT)


##### Plot #####
plotLabelFrame = Tk.LabelFrame(root, text='Step 2: Set plotting paramaters')
plotLabelFrame.pack(side=Tk.TOP, fill=Tk.X)
# Parameter: rows to skip
skipRowsFrame = Tk.Frame(plotLabelFrame)
skipRowsFrame.pack(side=Tk.TOP)
Tk.Label(skipRowsFrame, text='Lines to skip: ').pack(side=Tk.LEFT)
vSkipRows = Tk.IntVar(root)
vSkipRows.set(0)
entrySkipRows = Tk.Entry(skipRowsFrame, textvariable=vSkipRows, width=4)
entrySkipRows.pack(side=Tk.LEFT)

# Parameter: delimiter
delimiterFrame = Tk.Frame(plotLabelFrame)
delimiterFrame.pack(side=Tk.TOP)
Tk.Label(delimiterFrame, text='Delimiter: ').pack(side=Tk.LEFT)
vDelimiter = Tk.StringVar()
r1 = Tk.Radiobutton(delimiterFrame, text="Space/Tab", variable=vDelimiter, value='space')
r2 = Tk.Radiobutton(delimiterFrame, text="Comma", variable=vDelimiter, value='comma')
r1.select()
r2.deselect()
r1.pack(side=Tk.LEFT)
r2.pack(side=Tk.LEFT)

# Parameter: columns to draw
columnFrame = Tk.Frame(plotLabelFrame)
columnFrame.pack(side=Tk.TOP)
Tk.Label(columnFrame, text='Column number of x: ').pack(side=Tk.LEFT)
vColumnX = Tk.IntVar(root)
entryColumnX = Tk.Entry(columnFrame, textvariable=vColumnX, width=4)
vColumnX.set(1)
entryColumnX.pack(side=Tk.LEFT)
Tk.Label(columnFrame, text='Column number of y: ').pack(side=Tk.LEFT)
vColumnY = Tk.IntVar(root)
entryColumnY = Tk.Entry(columnFrame, textvariable=vColumnY, width=4)
vColumnY.set(2)
entryColumnY.pack(side=Tk.LEFT)

# Plot
def plot_data():
    '''
    A general method to plot the figure and create a new window to display
    '''
    # print(filename)
    if vDelimiter.get() == 'space':
        delimiter = None
    elif vDelimiter.get() == 'comma':
        delimiter = ','
    data = np.loadtxt(filename, skiprows=vSkipRows.get(), delimiter=delimiter)
    fig = Figure(figsize=(5, 4), dpi=100)
    axe = fig.add_subplot(111)
    axe.scatter(data[:, vColumnX.get()-1], data[:, vColumnY.get()-1])
    figWindowNew, canvasNew, toolbarNew = createFigWindow(fig)
    canvasNew.show()
    toolbarNew.update()
    # canvas._tkcanvas.pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)
    figWindowNew.wm_attributes('-topmost')  # Activate the plotting window

buttonReadData = Tk.Button(plotLabelFrame, text='Plot', command=plot_data)
buttonReadData.pack(side=Tk.TOP)


##### Background #####
bgLabelFrame = Tk.LabelFrame(root, text='Step 3: Determine the background')
bgLabelFrame.pack(side=Tk.TOP, fill=Tk.X)
# Parameter: fitting range
rangeFrame = Tk.Frame(bgLabelFrame)
rangeFrame.pack(side=Tk.TOP)

rangeStartFrame = Tk.Frame(rangeFrame)
rangeStartFrame.pack(side=Tk.TOP, anchor=Tk.W)
Tk.Label(rangeStartFrame, text='Background - Left zone:').pack(side=Tk.TOP, anchor=Tk.W)
Tk.Label(rangeStartFrame, text='x: from ').pack(side=Tk.LEFT)
vStartLeftX = Tk.DoubleVar(root)
entryStartLeftX = Tk.Entry(rangeStartFrame, textvariable=vStartLeftX, width=6)
entryStartLeftX.pack(side=Tk.LEFT)
Tk.Label(rangeStartFrame, text=' to ').pack(side=Tk.LEFT)
vStartRightX = Tk.DoubleVar(root)
entryStartRightX = Tk.Entry(rangeStartFrame, textvariable=vStartRightX, width=6)
entryStartRightX.pack(side=Tk.LEFT)

rangeEndFrame = Tk.Frame(rangeFrame)
rangeEndFrame.pack(side=Tk.TOP, anchor=Tk.W)
Tk.Label(rangeEndFrame, text='Background - Right zone:').pack(side=Tk.TOP, anchor=Tk.W)
Tk.Label(rangeEndFrame, text='x: from ').pack(side=Tk.LEFT)
vEndLeftX = Tk.DoubleVar(root)
entryEndLeftX = Tk.Entry(rangeEndFrame, textvariable=vEndLeftX, width=6)
entryEndLeftX.pack(side=Tk.LEFT)
Tk.Label(rangeEndFrame, text=' to ').pack(side=Tk.LEFT)
vEndRightX = Tk.DoubleVar(root)
entryEndRightX = Tk.Entry(rangeEndFrame, textvariable=vEndRightX, width=6)
entryEndRightX.pack(side=Tk.LEFT)

# Parameter: background form
bgFormFrame = Tk.Frame(bgLabelFrame)
bgFormFrame.pack(side=Tk.TOP)
Tk.Label(bgFormFrame, text='Background line shape: 1 for linear, 2 for parabola and n for higher rank polynomial').pack(side=Tk.TOP)
Tk.Label(bgFormFrame, text='Choice: ').pack(side=Tk.LEFT)
vPolynomial = Tk.IntVar(root)
vPolynomial.set(1)
entryPolynomial = Tk.Entry(bgFormFrame, textvariable=vPolynomial, width=4)
entryPolynomial.pack(side=Tk.LEFT)

def select_bg_data(data, selectRange):
    '''
    Select the data in a given range
    Input:
    data - a 2-colomn array
    selectRange - 4 points
    Output:
    outdata
    '''
    startLine1, startLine2 = None, None
    endLine1, endLine2 = None, None
    head1 = selectRange[0]
    head2 = selectRange[1]
    end1 = selectRange[2]
    end2 = selectRange[3]
    for i in xrange(data.shape[0]):
        if data[i, 0] >= head1 and startLine1 is None:
            startLine1 = i
        if startLine1 != None and startLine2 is None and data[i, 0] >= head2:
            startLine2 = i
        if data[i, 0] >= end1 and endLine1 is None:
            endLine1 = i
        if endLine1 != None and endLine2 is None and data[i, 0] >= end2:
            endLine2 = i
    x_bg = np.hstack((data[:, 0][startLine1:startLine2],
                      data[:, 0][endLine1:endLine2]))
    y_bg = np.hstack((data[:, 1][startLine1:startLine2],
                      data[:, 1][endLine1:endLine2]))
    return [x_bg, y_bg]

def fit_background():
    '''
    Fit the background
    '''
    bg_mod = PolynomialModel(vPolynomial.get(), prefix='bg_')   # Background
    if vDelimiter.get() == 'space':
        delimiter = None
    elif vDelimiter.get() == 'comma':
        delimiter = ','
    data = np.loadtxt(filename, skiprows=vSkipRows.get(), delimiter=delimiter)
    original_data = np.vstack((data[:, vColumnX.get()-1], data[:, vColumnY.get()-1])).T
    selectionRange = (vStartLeftX.get(), vStartRightX.get(), vEndLeftX.get(), vEndRightX.get())

    x_bg, y_bg = select_bg_data(original_data, selectionRange)

    pars = bg_mod.guess(y_bg, x=x_bg)
    mod = bg_mod
    init = mod.eval(pars, x=x_bg)
    out = mod.fit(y_bg, pars, x=x_bg)

    axe.cla()
    axe.plot(data[:, vColumnX.get()-1], data[:, vColumnY.get()-1], 'b.')
    axe.plot(x_bg, out.eval(), 'r-')    # Background plotting
    # axe.xlim([original_data[0, 0], original_data[1, -1]])
    figWindowNew, canvasNew, toolbarNew = createFigWindow(fig)
    canvasNew.show()
    toolbarNew.update()
    # canvas._tkcanvas.pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)
    figWindowNew.wm_attributes('-topmost')  # Activate the plotting window

buttonReadData = Tk.Button(bgLabelFrame, text='Fit background', command=fit_background)
buttonReadData.pack(side=Tk.TOP)

##### Integrate #####
intLabelFrame = Tk.LabelFrame(root, text='Step 4: Set integration range')
intLabelFrame.pack(side=Tk.TOP, fill=Tk.X)

# Parameter: integration range
intRangeFrame = Tk.Frame(intLabelFrame)
intRangeFrame.pack(side=Tk.TOP)

Tk.Label(intRangeFrame, text='x: from ').pack(side=Tk.LEFT)
vIntLeftX = Tk.DoubleVar(root)
entryIntLeftX = Tk.Entry(intRangeFrame, textvariable=vIntLeftX, width=6)
entryIntLeftX.pack(side=Tk.LEFT)
Tk.Label(intRangeFrame, text=' to ').pack(side=Tk.LEFT)
vIntRightX = Tk.DoubleVar(root)
entryIntRightX = Tk.Entry(intRangeFrame, textvariable=vIntRightX, width=6)
entryIntRightX.pack(side=Tk.LEFT)

def int_data():
    '''
    Integrate data in given area
    '''
    bg_mod = PolynomialModel(vPolynomial.get(), prefix='bg_')   # Background
    if vDelimiter.get() == 'space':
        delimiter = None
    elif vDelimiter.get() == 'comma':
        delimiter = ','
    data = np.loadtxt(filename, skiprows=vSkipRows.get(), delimiter=delimiter)
    original_data = np.vstack((data[:, vColumnX.get()-1], data[:, vColumnY.get()-1])).T
    selectionRange = (vStartLeftX.get(), vStartRightX.get(), vEndLeftX.get(), vEndRightX.get())

    x_bg, y_bg = select_bg_data(original_data, selectionRange)

    pars = bg_mod.guess(y_bg, x=x_bg)
    mod = bg_mod
    init = mod.eval(pars, x=x_bg)
    out = mod.fit(y_bg, pars, x=x_bg)

    x, y = data[:, vColumnX.get()-1], data[:, vColumnY.get()-1]

    comp = out.eval_components(x=x)
    out_param = out.params
    y_bg_fit = bg_mod.eval(params=out_param, x=x)
    y_bg_remove = y - y_bg_fit

    startLine, endLine = None, None
    for i in xrange(np.size(x)):
        if x[i] >= vIntLeftX.get() and startLine is None:
            startLine = i
        if startLine != None and endLine is None and x[i] >= vIntRightX.get():
            endLine = i
    x_int = x[startLine:endLine]
    y_int = y_bg_remove[startLine:endLine]
    y_bg_fit_ = y_bg_fit[startLine:endLine]
    y_orig = y[startLine:endLine]

    integration = np.trapz(y_int, x_int)

    # plot
    axe.cla()
    axe.plot(x, y, 'b.')
    axe.plot(x_bg, out.best_fit, 'r-')    # Background plotting
    # axe.xlim([x[0], x[-1]])
    axe.fill_between(x_int, y_orig, y_bg_fit_, facecolor='green')
    figWindowNew, canvasNew, toolbarNew = createFigWindow(fig)
    canvasNew.show()
    toolbarNew.update()
    # canvas._tkcanvas.pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)
    figWindowNew.wm_attributes('-topmost')  # Activate the plotting window

    # report
    reportWindow = Tk.Tk()
    report = 'Integration area = ' + repr(integration)
    reportText = Tk.Text(reportWindow)
    reportText.insert(Tk.INSERT, report)
    reportText.pack()
    reportWindow.wm_attributes('-topmost')



buttonIntegrate = Tk.Button(intLabelFrame, text='Integrate', command=int_data)
buttonIntegrate.pack(side=Tk.TOP)

##########
def on_key_event(event):
    print('you pressed %s' % event.key)
    key_press_handler(event, canvas, toolbar)

canvas[-1].mpl_connect('key_press_event', on_key_event)


def _quit():
    root.quit()     # stops mainloop
    root.destroy()  # this is necessary on Windows to prevent
                    # Fatal Python Error: PyEval_RestoreThread: NULL tstate



button = Tk.Button(root, text='Quit', command=_quit)
button.pack(side=Tk.TOP)

Tk.mainloop()
# If you put root.destroy() here, it will cause an error if
# the window is closed with the window manager.